name: ShelfX CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Backend Setup and Tests
      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      # - name: Run backend tests
      #   run: |
      #     cd backend
      #     npm test

      # Frontend Setup and Tests
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      # - name: Run frontend tests
      #   run: |
      #     cd frontend
      #     npm run test

      # Optional: Audit (Non-blocking)
      - name: Run audit (non-blocking)
        run: npm audit || true

      # Optional: Build Frontend
      - name: Build frontend
        run: |
          cd frontend
          npm run build

      # Optional: Deploy (replace with your actual command)
      - name: Deploy to production
        run: |
          echo "✅ Build successful. Deploy step goes here."